spring:
  data:
    mongodb:
      uri: mongodb://admin:123456@192.168.1.100:27017/testdb?authSource=admin
#      authSource=admin\u5FC5\u52A0
#spring:
#  data:
#    mongodb:
#      host: 192.168.1.100
#      port: 27017
#      database: testdb
#      username: admin
#      password: '123456'